
    opts = fitoptions('Method','NonlinearLeastSquares',...
               'Lower',[0,10,0],...
               'Upper',[10^8,1500,10],...
               'StartPoint',[10^5,200,1.2]);
    LORENTZIAN = fittype( @(A, Fo, Q, x) ...
        (A./(((Fo./(2*pi)).^2 - (x./(2*pi)).^2).^2+(x.*Fo/(4*pi.^2*Q)).^2)),...
        'options',opts);

    fitObj = fit(F,(P), LORENTZIAN,...
        'Weights',1./log10(F),'Normalize','off',...
        'TolFun',10^-12,'TolX',10^-12,'Robust','on')
    
    loglog(F,P,'b');
    hold on;
    Pmodel = feval(fitObj,F);
    loglog(F,Pmodel,'r');
    xlim([50 1500]);